name: PUSH

on: workflow_dispatch
  # schedule:
  #   - cron: '1-59/2 * * * *'
  # wor
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install requests
        python main.py --username=adhityappeo --file=out.json
    - name: Deploy Files
      run: |
      bash script.sh